### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by hsnthn**
Updated readme and jira information added

### CODE REVIEW

**Comment by furkanvarol** [comment]
Can you also add license badge below?

[License](http://badges.mit-license.org)

`[License](http://badges.mit-license.org)`

**Comment by hsnthn** [comment]
@furkanvarol added

**Comment by furkanvarol** [comment]
Can you make commit message's first character capitalized? Also, can you update the title [SETL-???] according to JIRA issue number?

**Comment by furkanvarol** [comment]
@kubudi can you check this PR? You had some opinion abut README.

**Comment by msimav** [comment]
@hsnthn And can you make commit message more informative.

**Pull request closed without merging**
